backend:
  name: github
  repo: duydo/duydo.github.io

media_folder: "static/images" # Nơi lưu hình ảnh hoặc tài nguyên
public_folder: "/uploads"

collections:
  - name: "blog" # Tên collection
    label: "Blog"
    folder: "content/posts" # Thư mục lưu trữ file markdown
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
